apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: influxdb-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: ext4
    volumeID: f30253d6-d214-46c6-b796-53fc37cfec87

