apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-1
  labels:
    type: grafana-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: ext4
    volumeID: 0f492831-91c5-48b3-8239-ab65edd58cfb
